name: "Build + upload."
on:
  push:
    branches:
      # Run on push to main.
      - main
  schedule:
    # Run every day at 00:00 UTC (midnight)
    - cron: "0 0 * * *"
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev
            sdk-channel: dev
          - name: release
            sdk-channel: release
    name: "ufbt: Build for ${{ matrix.name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          app-dir: ./fap
          sdk-channel: ${{ matrix.sdk-channel }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.name }}-${{ steps.build-app.outputs.suffix }}.zip
          path: ${{ steps.build-app.outputs.fap-artifacts }}
